#!/usr/bin/env python

import sys
import os
import glob

def main(filename):
    filepath = os.getcwd() + "/.versiondir/" + filename

    # print(os.getcwd() + "/.versiondir/" + str(filename))

    if not (os.path.exists(filepath)):
        sys.exit("ERROR: file does not exist! Make sure you are referencing a file that exists.")
    else :
        filesList = glob.glob1(os.path.dirname(filepath), "." + filename + ".[0-9]")
        filesList.sort()

        for x in filesList:
            print(x[1:])

if __name__ == '__main__':
    if not (len(sys.argv) == 2):
        sys.exit("ERROR: Incorrect number of arguments given, please enter a valid filename.")
    main(sys.argv[1])