#!/bin/bash

versiondir="$PWD/.versiondir"
mountdir="$PWD/mount"

if [ -d "$mountdir" ]; then
	# Control will enter here if $mountdir exists.
	fusermount -u mount
fi

if [ -d "$versiondir" ]; then
	# Control will enter here if $versiondir exists.
	rm -fr $versiondir
fi

if [ -d "$mountdir" ]; then
	# Control will enter here if $mountdir exists.
	rm -fr $mountdir
fi



